### ISSUE TITLE
Gemが更新されていません

### ISSUE THREAD

**Issue by kichion** [holiday-jp/holiday_jp-ruby#34]
https://rubygems.org/gems/holiday_jp/versions/0.7.0
私が確認した限り、今年の祝日がGemにはまだ反映されていませんでした

**Comment by MasahiroMorita** [comment]
ぜひ、更新お願いします！

**Comment by k1LoW** [comment]
@komagata 
こちら対応をお願いできますかー？
もしくは、Gemのリリース権もらえたら対応しておきますー 🙇

**Comment by komagata** [comment]
@k1LoW すみません、了解しました。
少々お待ちいただければー

**Comment by komagata** [comment]
@kichion @MasahiroMorita @k1LoW リリース致しました。

[holiday\_jp \| RubyGems\.org \| your community gem host](https://rubygems.org/gems/holiday_jp)

**Comment by kichion** [comment]
ありがとうございます！確認しました！
